# Generated by Django 4.0 on 2022-01-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_language', models.CharField(max_length=10, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(null=True)),
                ('popularity', models.FloatField()),
                ('runtime', models.IntegerField(null=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_count', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movie.Genre')),
                ('keywords', models.ManyToManyField(related_name='movies', to='movie.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_cos', models.FloatField()),
                ('from_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_movie', to='movie.movie')),
                ('to_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_movie', to='movie.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='similarities',
            field=models.ManyToManyField(related_name='similar_to+', through='movie.Similarity', to='movie.Movie'),
        ),
    ]
