# Generated by Django 4.0 on 2022-01-17 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
        ('movie', '0002_movierating_movie_user_ratings_movierating_movie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='user_ratings',
            field=models.ManyToManyField(through='movie.MovieRating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movie.movie'),
        ),
        migrations.AlterField(
            model_name='movierating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='accounts.useraccount'),
        ),
    ]
